directory: /home/beets/music
library: /home/beets/music/beet-library.db
plugins: convert info musicbrainz
asciify_paths: yes
format_item: $artist - $album - $title ($format $bitrate $samplerate $bitdepth)
convert:
  copy_album_art: yes
  never_convert_lossy_files: yes
  formats:
    cd:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
      extension: flac
    cd_with_dither:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 -dither_method triangular $dest
      extension: flac

